### ISSUE TITLE
Scrolling child nodes

### ISSUE THREAD

**Issue by krutoo** [rick-liruixin/body-scroll-lock-upgrade#12]
Hi, first of all thanks for creating this fork

In my case i have modal with input with autocomplete dropdown menu.

Dropdown can have it's own scroll.

How to configure `body-scroll-lock-upgrade` for this case?

**Comment by rick-liruixin** [comment]
> Hi, first of all thanks for creating this fork
> 
> In my case i have modal with input with autocomplete dropdown menu.
> 
> Dropdown can have it's own scroll.
> 
> How to configure `body-scroll-lock-upgrade` for this case?

hello, For your question, I have written an example, you can refer to https://github.com/rick-liruixin/body-scroll-lock-upgrade/blob/develop/examples/vanilla-js/index.html    @krutoo

**Comment by rick-liruixin** [comment]
> Hi, first of all thanks for creating this fork
> 
> In my case i have modal with input with autocomplete dropdown menu.
> 
> Dropdown can have it's own scroll.
> 
> How to configure `body-scroll-lock-upgrade` for this case?

It seems your problem has been solved, I closed this comment. @krutoo 
https://github.com/willmcpo/body-scroll-lock/issues/257

**Comment by krutoo** [comment]
@rick-liruixin But in your example there is no dropdown elements in modal dialog
