### ISSUE TITLE
Request for UMD file

### ISSUE THREAD

**Issue by harumijang** [rick-liruixin/body-scroll-lock-upgrade#13]
Hi, we would like to use your library in the Drupal project but Drupal can't use use esm module. Would you be able to provide a UMD file for this library?

**Comment by rick-liruixin** [comment]
> Hi, we would like to use your library in the Drupal project but Drupal can't use use esm module. Would you be able to provide a UMD file for this library?

I am very sorry that there is no such way at present. I will arrange it as soon as possible in my spare time. I will send you a message under this issue then @harumijang

**Comment by rick-liruixin** [comment]
> Hi, we would like to use your library in the Drupal project but Drupal can't use use esm module. Would you be able to provide a UMD file for this library?

Added, example：https://github.com/rick-liruixin/body-scroll-lock-upgrade/blob/develop/examples/vanilla-js/index-umd.html @harumijang
