### ISSUE TITLE
Using logical css property instead of padding-right

### ISSUE THREAD

**Issue by functionalDev** [rick-liruixin/body-scroll-lock-upgrade#20]
### Current
For the option `reserveScrollBarGap` a **padding-right** is set on `document.body`, which is not considering the flow/writing direction (css property `direction`)

### Proposed
Instead of setting the `padding-right` the corresponding logical css-property is set on `document.body`: **padding-inline-end**

**Comment by rick-liruixin** [comment]
> ### Current
> For the option `reserveScrollBarGap` a **padding-right** is set on `document.body`, which is not considering the flow/writing direction (css property `direction`)
> 
> ### Proposed
> Instead of setting the `padding-right` the corresponding logical css-property is set on `document.body`: **padding-inline-end**

@functionalDev  More functionality can be packaged without using the component's original functionality
