### ISSUE TITLE
allowTouchMove type is wrong

### ISSUE THREAD

**Issue by ghsteff** [rick-liruixin/body-scroll-lock-upgrade#21]
allowTouchMove is typed `allowTouchMove: (el: EventTarget) => boolean`, but should be `allowTouchMove: (el: HTMLElement) => boolean` based off example usage.

```
disableBodyScroll(container, {
  allowTouchMove: (el) => {
    while (el && el !== document.body) {
      if (el.getAttribute('body-scroll-lock-ignore') !== null) {
        return true;
      }

      el = el.parentElement;
    }
  },
});
```

This example usage works for me, but ts complains

**Comment by JZ-WooliesX** [comment]
same here need to do a cast  `let element = el as Element;`

**Comment by aalyokhin** [comment]
@ghsteff faced with this today and I don't think this is something that can be fixed. The type comes from the fact that there's a callback function for the `touchmove` event, so the `event.target` is typed correctly:

https://github.com/rick-liruixin/body-scroll-lock-upgrade/blob/10bfd2678c1c29a265b2847e5203a142da0fa63b/src/body-scroll-lock.ts#L286-L288

For myself, I fixed it in this way:

```TS
- while (el && el !== document.body) {
+ while (el && el !== document.body && el instanceof HTMLElement) {
```
