### ISSUE TITLE
Sticky component dissappears when scroll-lock is active

### ISSUE THREAD

**Issue by sergio-sanchez-check24** [rick-liruixin/body-scroll-lock-upgrade#22]
Hi,

Im having an issue with iOS mobile devices where, if I have elsewhere in the DOM an element with `position: sticky;`, when I open a modal wich has an overlay, and this overlay has the scroll-lock active, the sticky goes to the bottom of the page till I dont close the modal. From what I see, on iOS mobile devices, the <body> tag gets `position: fixed` (among other properties) when the scroll-lock is active, maybe it could be related to this but i'm not 100% sure

**Comment by rick-liruixin** [comment]
The use of position: fixed; will inevitably cause position: sticky; to become ineffective.
@sergio-sanchez-check24
