### ISSUE TITLE
Please use <html> instead of <body>

### ISSUE THREAD

**Issue by VityaSchel** [rick-liruixin/body-scroll-lock-upgrade#8]
body is not always stopping scrolling, but setting `overflow: hidden` on html tag does

**Comment by rick-liruixin** [comment]
> body is not always stopping scrolling, but setting `overflow: hidden` on html tag does

Let me have a look at your specific problem and code demo

**Comment by christophstockinger** [comment]
I can confirm this. I added your package to the next.js app and call `disableBodyScroll(targetRef.current)`. It added the `overflow: hidden` to the `document.body` but scrolling is not disabeld. If I added it manually to the `html`-tag it works.

**Comment by rick-liruixin** [comment]
> I can confirm this. I added your package to the next.js app and call `disableBodyScroll(targetRef.current)`. It added the `overflow: hidden` to the `document.body` but scrolling is not disabeld. If I added it manually to the `html`-tag it works.

I tried it as you said, and found that when the next.js project initializes, it adds overflow-x: hidden to html and body; Just hide it. You need to see if body and html use overflow: hidden;

Example: https://github.com/rick-liruixin/body-scroll-lock-upgrade/blob/develop/examples/next/app/globals.css

**Comment by rick-liruixin** [comment]
> body is not always stopping scrolling, but setting `overflow: hidden` on html tag does

You need to see if body and html use overflow: hidden; He'll cause the lock to fail

**Comment by rick-liruixin** [comment]
> body is not always stopping scrolling, but setting `overflow: hidden` on html tag does

You need to see if body and html use overflow: hidden; He'll cause the lock to fail @VityaSchel

**Comment by mrleblanc101** [comment]
@rick-liruixin 
Why was this closed ?
If we use `overflow-x: hidden;` on the HTML, the lib should add `overflow: hidden;` to the `<html>` instead of the `<body>`.
Otherwise, it doesn't work.
It should at least be a configurable option, unless it create issue elsewhere.
