### ISSUE TITLE
plain javascript build

### ISSUE THREAD

**Issue by jardakotesovec** [rick-liruixin/body-scroll-lock-upgrade#9]
Hi Rick,
thanks a lot for picking this up since the original package was abandoned.

My use case (of original package) was to use plain javascript file (https://github.com/rick-liruixin/body-scroll-lock-upgrade/tree/develop#vanilla-js) that can be used as global variable as I have simple use case without build step.

Would be possible to ship such build as well? 

Thank you for feedback.
Jarda

**Comment by rick-liruixin** [comment]
> Hi Rick, thanks a lot for picking this up since the original package was abandoned.
> 
> My use case (of original package) was to use plain javascript file (https://github.com/rick-liruixin/body-scroll-lock-upgrade/tree/develop#vanilla-js) that can be used as global variable as I have simple use case without build step.
> 
> Would be possible to ship such build as well?
> 
> Thank you for feedback. Jarda

I am very sorry that there is no such way at present. I will arrange it as soon as possible in my spare time. I will send you a message under this issue then @jardakotesovec

**Comment by rick-liruixin** [comment]
> @rick-liruixin Thank you for getting back to me quickly!
> 
> Eventually I decided that it actually will be better for me to include it via npm and add build step to my app to combine few of these dependencies, rather than keeping them as individual JS files.
> 
> It still might be useful for others, but wanted to clarify that I don't need this option anymore.


```javascript

<script type="module">
  // https://cdn.jsdelivr.net/gh/rick-liruixin/body-scroll-lock-upgrade@v1.0.3.1/lib/index.esm.js

  import {
    clearAllBodyScrollLocks,
    disableBodyScroll,
    enableBodyScroll,
  } from "https://cdn.jsdelivr.net/gh/rick-liruixin/body-scroll-lock-upgrade@v1.0.3.1/lib/index.esm.js";

  // 1. Get a target element that you want to persist scrolling for (such as a modal/lightbox/flyout/nav).
  // Specifically, the target element is the one we would like to allow scroll on (NOT a parent of that element).
  // This is also the element to apply the CSS '-webkit-overflow-scrolling: touch;' if desired.
  const targetElement = document.querySelector("#someElementId");

  // 2. ...in some event handler after showing the target element...disable body scroll
  disableBodyScroll(targetElement);

  // 3. ...in some event handler after hiding the target element...
  enableBodyScroll(targetElement);

  // 4. Useful if we have called disableBodyScroll for multiple target elements,
  // and we just want a kill-switch to undo all that.
  clearAllBodyScrollLocks();

</script>

```
